services:
  sitemap-monitor:
    build: .
    container_name: sitemap_monitor
    restart: unless-stopped
    ports:
      - "8000:8000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      - TZ=Asia/Shanghai
      - DB_TYPE=mysql
      - DB_HOST=superfa_mysql
      - DB_PORT=3306
      - DB_USER=n8n_superfa
      - DB_PASSWORD=Abc@911911
      - DB_NAME=sitemapmonitor
    volumes:
      - ./data:/app/data           # 数据持久化目录
      - ./latest:/app/latest       # 最新数据JSON文件
      - ./config.yaml:/app/config.yaml
    networks:
      - db_network

networks:
  db_network:
    external: true
